// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhwMMTxb3y0iaaDtItVb2a5VEC4SabQ48',
    appId: '1:942479130967:web:65d0daf4a07dc2e323fe12',
    messagingSenderId: '942479130967',
    projectId: 'todoapptut',
    authDomain: 'todoapptut.firebaseapp.com',
    storageBucket: 'todoapptut.appspot.com',
    measurementId: 'G-JZF9V89TRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdXQwiSxcVKnSybetZWiRWm2Psnc-PV8k',
    appId: '1:942479130967:android:1737c81380286e9123fe12',
    messagingSenderId: '942479130967',
    projectId: 'todoapptut',
    storageBucket: 'todoapptut.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFc1WU8G0Auu_3x0Zal5EKL8JM8E7wwGw',
    appId: '1:942479130967:ios:a3446493fe910e3a23fe12',
    messagingSenderId: '942479130967',
    projectId: 'todoapptut',
    storageBucket: 'todoapptut.appspot.com',
    androidClientId: '942479130967-ni3a38f4gkr86dge1i1si7n4d0ki19k0.apps.googleusercontent.com',
    iosClientId: '942479130967-6h176l5jnv3u62h4h6a6tbqb4438s1gs.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoMain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFc1WU8G0Auu_3x0Zal5EKL8JM8E7wwGw',
    appId: '1:942479130967:ios:b526d11d99bccac023fe12',
    messagingSenderId: '942479130967',
    projectId: 'todoapptut',
    storageBucket: 'todoapptut.appspot.com',
    androidClientId: '942479130967-ni3a38f4gkr86dge1i1si7n4d0ki19k0.apps.googleusercontent.com',
    iosClientId: '942479130967-0vg1puiudt0tcrl0h2f4uqb4lqrbf0n7.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoMain.RunnerTests',
  );
}
